services:
  web:
    container_name: web
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
    hostname: "algo.example.com"
  sql:
    container_name: sql
    image: "mysql:8"
    ports:
      - "3306:3306"
    volumes:
      - ../mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes