
DROP DATABASE IF EXISTS games;
DROP USER IF EXISTS 'games'@'%';
CREATE USER IF NOT EXISTS 'games'@'%' identified by 'gamespass';
GRANT ALL PRIVILEGES ON games.* to 'games'@'%';

CREATE DATABASE games;
USE games;

CREATE TABLE usuario (
  `ID` int NOT NULL AUTO_INCREMENT,
  `EMAIL` varchar(128) COLLATE utf8mb4_general_ci NOT NULL,
  `NICK` varchar(32) COLLATE utf8mb4_general_ci NOT NULL,
  `ROLE` varchar(32) COLLATE utf8mb4_general_ci NOT NULL,
  `NOMBRE` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  `APELLIDOS` varchar(128) COLLATE utf8mb4_general_ci NOT NULL,
  `PASSWORD` varchar(128) COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `email` (`EMAIL`),
  UNIQUE KEY `nick` (`NICK`)
);

CREATE TABLE tarjeta_bancaria (
  `NUMERO` int NOT NULL,
  `CVV` int DEFAULT NULL,
  `FECHA_CADUC` date DEFAULT NULL,
  `ID_USUARIO` int DEFAULT NULL,
  PRIMARY KEY (`NUMERO`),
  KEY `FK_TAR_IDUS_USU_ID` (`ID_USUARIO`),
  CONSTRAINT `FK_TAR_IDUS_USU_ID` FOREIGN KEY (`ID_USUARIO`) REFERENCES `usuario` (`ID`)
);

CREATE TABLE juego (
  `ID` int NOT NULL,
  `TITULO` varchar(32) COLLATE utf8mb4_general_ci NOT NULL,
  `RUTA` varchar(128) COLLATE utf8mb4_general_ci NOT NULL,
  `DESARROLLADOR` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  `DISTRIBUIDOR` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  `ANIO` year NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `RUTA` (`RUTA`)
);

CREATE TABLE regala (
  `ID_JUEGO` int NOT NULL,
  `ID_US1` int NOT NULL,
  `ID_US2` int NOT NULL,
  `FECHA` date NOT NULL,
  PRIMARY KEY (`ID_JUEGO`,`ID_US1`,`ID_US2`),
  KEY `FK_REG_IDU1_USU_ID` (`ID_US1`),
  KEY `FK_REG_IDU2_USU_ID` (`ID_US2`),
  CONSTRAINT `FK_REG_IDJ_JUE_ID` FOREIGN KEY (`ID_JUEGO`) REFERENCES `juego` (`ID`),
  CONSTRAINT `FK_REG_IDU1_USU_ID` FOREIGN KEY (`ID_US1`) REFERENCES `usuario` (`ID`),
  CONSTRAINT `FK_REG_IDU2_USU_ID` FOREIGN KEY (`ID_US2`) REFERENCES `usuario` (`ID`)
);

CREATE TABLE presta (
  `ID_JUEGO` int NOT NULL,
  `ID_U1` int NOT NULL,
  `ID_U2` int NOT NULL,
  `FECHA` date NOT NULL,
  PRIMARY KEY (`ID_JUEGO`,`ID_U1`,`ID_U2`,`FECHA`),
  KEY `FK_PRES_IDU1_USU_ID` (`ID_U1`),
  KEY `FK_PRES_IDU2_USU_ID` (`ID_U2`),
  CONSTRAINT `FK_PRES_IDJ_JUE_ID` FOREIGN KEY (`ID_JUEGO`) REFERENCES `juego` (`ID`),
  CONSTRAINT `FK_PRES_IDU1_USU_ID` FOREIGN KEY (`ID_U1`) REFERENCES `usuario` (`id`),
  CONSTRAINT `FK_PRES_IDU2_USU_ID` FOREIGN KEY (`ID_U2`) REFERENCES `usuario` (`id`)
);

CREATE TABLE posee (
  `ID_USUARIO` int NOT NULL,
  `ID_JUEGO` int NOT NULL,
  `FECHA` date NOT NULL,
  PRIMARY KEY (`ID_USUARIO`,`ID_JUEGO`),
  KEY `FK_COMP_IDJU_JUE_ID` (`ID_JUEGO`),
  CONSTRAINT `FK_COMP_IDJU_JUE_ID` FOREIGN KEY (`ID_JUEGO`) REFERENCES `juego` (`ID`),
  CONSTRAINT `FK_COMP_IDUS_USU_ID` FOREIGN KEY (`ID_USUARIO`) REFERENCES `usuario` (`ID`)
);

CREATE TABLE genero (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(32) COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE juego_genero (
  `ID_JUEGO` int NOT NULL,
  `ID_GENERO` int NOT NULL,
  PRIMARY KEY (`ID_JUEGO`,`ID_GENERO`),
  KEY `FK_JGEN_IDJ_GEN_ID` (`ID_GENERO`),
  CONSTRAINT `FK_JGEN_IDJ_GEN_ID` FOREIGN KEY (`ID_GENERO`) REFERENCES `genero` (`ID`),
  CONSTRAINT `FK_JGEN_IDJ_JUE_ID` FOREIGN KEY (`ID_JUEGO`) REFERENCES `juego` (`ID`)
);

CREATE TABLE `genero_genero` (
  `ID_G1` int NOT NULL,
  `ID_G2` int NOT NULL,
  PRIMARY KEY (`ID_G1`,`ID_G2`),
  CONSTRAINT `FK_GREL_IDG1_GEN_ID` FOREIGN KEY (`ID_G1`) REFERENCES `genero` (`ID`)
);

CREATE TABLE sistema (
  `ID` int NOT NULL AUTO_INCREMENT,
  `nombre` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE juego_sistema (
  `ID_JUEGO` int NOT NULL,
  `ID_SIST` int NOT NULL,
  PRIMARY KEY (`ID_JUEGO`,`ID_SIST`),
  KEY `FK_JSIST_IDJ_SIST_ID` (`ID_SIST`),
  CONSTRAINT `FK_JSIST_IDJ_JUE_ID` FOREIGN KEY (`ID_JUEGO`) REFERENCES `juego` (`ID`),
  CONSTRAINT `FK_JSIST_IDJ_SIST_ID` FOREIGN KEY (`ID_SIST`) REFERENCES `sistema` (`ID`)
);

CREATE TABLE `juego_juego` (
  `ID_J1` int NOT NULL,
  `ID_J2` int NOT NULL,
  PRIMARY KEY (`ID_J1`,`ID_J2`),
  KEY `FK_JREL_IDJ2_JUE_ID` (`ID_J2`),
  CONSTRAINT `FK_JREL_IDJ1_JUE_ID` FOREIGN KEY (`ID_J1`) REFERENCES `juego` (`ID`),
  CONSTRAINT `FK_JREL_IDJ2_JUE_ID` FOREIGN KEY (`ID_J2`) REFERENCES `juego` (`ID`)
);

INSERT INTO usuario(EMAIL, NICK, NOMBRE, APELLIDOS, PASSWORD, ROLE) VALUES('user@gmail.com','user','user','user','$2a$12$/.57XI5riojUPwXeoQXX9O/ru1XsQ5MRSsj8lZAo85sJb2b0tbEsi', 'user');
INSERT INTO usuario(EMAIL, NICK, NOMBRE, APELLIDOS, PASSWORD, ROLE) VALUES('admin@gmail.com','admin','admin','admin','$2y$10$xiAIe5dxN/fi39Jq08f1nu3BLCnuU7OBhcHoDcuDnVNJqtrOZUJzK', 'admin');
INSERT INTO juego (ID, TITULO, RUTA, DESARROLLADOR, DISTRIBUIDOR, ANIO) VALUES (150886, 'Truck Racer', 'algo', 'Kylotonn Entertainment', 'Plug In Digital SAS',2013);
INSERT INTO juego (ID, TITULO, RUTA, DESARROLLADOR, DISTRIBUIDOR, ANIO) VALUES (63690, 'Pako 2', 'algo2', 'Uranium Software', 'Uranium Software',1995);
INSERT INTO juego (ID, TITULO, RUTA, DESARROLLADOR, DISTRIBUIDOR, ANIO) VALUES (136678, 'Afterparty', 'algo3', 'Night School Studio, LLC', 'Night School Studio, LLC',2020);
INSERT INTO juego (ID, TITULO, RUTA, DESARROLLADOR, DISTRIBUIDOR, ANIO) VALUES (73736, 'Tengami', 'algo4', 'Nyamyam Ltd.', 'Nyamyam Ltd.',2014);
INSERT INTO juego (ID, TITULO, RUTA, DESARROLLADOR, DISTRIBUIDOR, ANIO) VALUES (190922, 'Oxenfree II: Lost Signals', 'algo5', 'Night School Studio, LLC', 'Netflix Inc.',2023);
INSERT INTO posee(ID_USUARIO, ID_JUEGO, FECHA) VALUES (1,150886, date(now()));
INSERT INTO posee(ID_USUARIO, ID_JUEGO, FECHA) VALUES (1,63690, date(now()));

INSERT INTO genero(ID, NOMBRE) VALUES (1, 'Action');
